### ISSUE TITLE
Zabbix-agent fica offline para o zabbix-server

### ISSUE THREAD

**Issue by empereira** [isaqueprofeta/zabbix-lab#1]
Buenas @isaqueprofeta , tudo tranquilo?

Cara, estou com um lab com teu docker-compose.yml e a principio tudo subiu like a charm.

O conteúdo dos volumes é que não estão aparecendo. Acredito que tenha que mapear o conteúdo pros volumes, não é?

Outro ponto é que o zabbix-agent fica offline para o zabbix-server.

**Comment by isaqueprofeta** [comment]
Se você esperar uns 30 segundos à um minuto, o agent atualiza e fica certinho.

Fora isso este projeto é um laboratório e não tem como objetivo subir volumes muito específicos, isso vai da necessidade de cada um.

**Comment by empereira** [comment]
> Se você esperar uns 30 segundos à um minuto, o agent atualiza e fica certinho.

O meu fazem 3 horas e ainda mostra no dashboard como offline

> Fora isso este projeto é um laboratório e não tem como objetivo subir volumes muito específicos, isso vai da necessidade de cada um.

Tranquilo, mas deveria ter conteúdo nos volumes? Nos teus testes, tinha conteúdo?

**Comment by isaqueprofeta** [comment]
Não tem conteúdo porque no zabbix original não tem uai... Isso não é implicito da ferramenta?

**Comment by isaqueprofeta** [comment]
Meu projeto é apenas uma extração de lab do original, acredito que para você tirar melhor suas dúvidas seja melhor você pegar direto na fonte: https://github.com/zabbix/zabbix-docker

**Comment by empereira** [comment]
> Meu projeto é apenas uma extração de lab do original, acredito que para você tirar melhor suas dúvidas seja melhor você pegar direto na fonte: https://github.com/zabbix/zabbix-docker

Blz. Vlw pela ajuda!!

**Comment by isaqueprofeta** [comment]
Reabrindo issue, identifiquei que o Agent não carregava a monitoração devido falha na execução do provisionamento que não estava funcionando para redirecionar para o agente do docker.

Por algum motivo ou atualização a pyzabbix estava falhando já na criação do objeto ZabbixAPI, bastou colocar a criação do objeto dentro do while que aguarda o frontend ficar disponível.

https://github.com/isaqueprofeta/zabbix-lab/blob/36b067f9fd6c517ff9d92085976b30add230ed78/zabbix/provisioning.py#L23-L38
