### ISSUE TITLE
Menu Services/Services em branco

### ISSUE THREAD

**Issue by filldeveloper** [isaqueprofeta/zabbix-lab#2]
Após a criação de um serviço no submenu services, a página fica em branco. A página volta a ser exibida após a deleção do serviço criado

**Comment by isaqueprofeta** [comment]
Bug específico no próprio zabbix na versão 6.0.4, tente mudar a ZABBIX_VERSION no .env de 6.0-latest para 6.0.0 por exemplo e faça novamente o docker-compose pull.

**Comment by isaqueprofeta** [comment]
Atualização, testei aqui e acho que é problema na publicação do docker do Zabbix. A tag de 6.0 latest parece estar misturada com a trunk, se quiser pode usar 6.0.4 na versão que vai funcionar.

Já avisei a zabbix no bug https://support.zabbix.com/browse/ZBX-21113
