### ISSUE TITLE
Install where grafana container already exists

### ISSUE THREAD

**Issue by christyler80** [isaqueprofeta/zabbix-lab#3]
Would you expect zabbix-lab to work on a raspberry Pi 4?

I already have some grafana dashboards running on my Pi. How I can modify the install scripts to add zabbiz-lab to my existing setup? I am a newbie to docker, so apologies if my question is a bit weird!!

Many thanks for your work on this and best wishes for 2023.

**Comment by isaqueprofeta** [comment]
As it is, I expect it not to work. Raspberry is an ARM architecture processor, you'll want docker images thar are specific to it.

You can try to search and replace the docker-compose images for each service and the base image on Dockerfile of zapix to match your processor.

It's not a problem that I wish to address, I dont like zabbix database to be on a raspberry sd card, so I will close the issue.

**Comment by christyler80** [comment]
Thank you for your reply.
