### ISSUE TITLE
novo no zabbix

### ISSUE THREAD

**Issue by hiagocosta** [isaqueprofeta/zabbix-lab#4]
man, tudo bem?
sou novo no zabbix e na programação, queria tirar uma duvida com vc sobre como acessar o painel desse lab

visto que não publica nenhuma porta, não sei como acessar o painel desse conjunto, poderia me ajudar?

**Comment by isaqueprofeta** [comment]
Todas as URL's estão na parte de ["Contents"](https://github.com/isaqueprofeta/zabbix-lab/blob/main/README.md#contents) cara.

- Zabbix:
  - Zabbix Server at: zabbix-server:10051
  - Zabbix Agent at: zabbix-agent:10050
  - Zabbix Frontend at: [http://zabbix-frontend:8080](http://zabbix-frontend:8080)
- Database:
  - Postgresql at: postgresql:5432
  - PGAdmin at: [http://pgadmin:5050](http://pgadmin:5050)
  - TimescaleDB extension installed
- Support Tools:
  - Zapix at: [http://zapix](http://zap)
  - Grafana at: [http://grafana:3000](http://grafana:3000)
  - Mailhog at: [http://mailhog:8025](http://mailhog:8025)

Se por acaso não ficou claro, o docker-hoster pega a configuração do service hostname e publica no hosts da máquina local. Então é só usar o nome do service como DNS para acessar.

Dá uma lida nos três últimos bullets do ["How To Use"](https://github.com/isaqueprofeta/zabbix-lab#how-to-use), eles explicam exatamente a configuração para isso:

**Comment by isaqueprofeta** [comment]
- Start the docker hoster for easy access using local DNS:

  ```sh
  docker run -d \
      --restart=always \
      -v /var/run/docker.sock:/tmp/docker.sock \
      -v /etc/hosts:/tmp/hosts \
      dvdarias/docker-hoster
  ```

- Start the project with docker-compose

  ```sh
  docker-compose up -d
  ```

- **Note** that docker **will not use 'localhost'** so, do not use that 'localhost' hostname to configure PGAdmin to PostgreSQL and Mailhog. To do this configuration, look at hostname option for each container, inside docker-compose.yml file.

**Comment by isaqueprofeta** [comment]
- Iniciar o gestor do hosts para facilitar acesso:

  ```sh
  docker run -d \
    -v /var/run/docker.sock:/tmp/docker.sock \
    -v /etc/hosts:/tmp/hosts \
    dvdarias/docker-hoster
  ```

- Iniciar o projeto com o docker-compose

  ```sh
  docker-compose up -d
  ```

- **Observe** que a estrutura em docker **não usa 'localhost'** então não use esse hostname 'localhost' para configurar o PGAdmin para PostgreSQL e no mailhog. Para configurar os mesmos, atentar-se para a opção de hostname para cada contêiner dentro da configuração do arquivo docker-compose.yml.

**Comment by isaqueprofeta** [comment]
Acho que isso é suficiente, então vou fechar a Issue, uma vez que já existe documentação no ["How To Use"](https://github.com/isaqueprofeta/zabbix-lab#how-to-use)

Outra coisa importante @hiagocosta: Não use o projeto se você é iniciante em Zabbix E Docker. Não é uma boa ideia, muitos conceitos novos de uma vez só.

Para fechar, vou reforçar: não use esse projeto em produção do jeito que ele está... isso aqui é um Lab de estudos.

**Comment by isaqueprofeta** [comment]
Se por acaso não ficou claro, o docker-hoster pega a configuração do service hostname e publica no hosts da máquina local. Então é só usar o nome do service como DNS para acessar.

**Comment by isaqueprofeta** [comment]
Para fechar, vou reforçar: não use esse projeto em produção do jeito que ele está... isso aqui é um Lab de estudos.
